# folder settings
source: .
destination: ./_site

# site settings
markdown: rdiscount

# site url
url: sparanoid.com/lab/start

# used by images inserted in posts
file: http://rsrc.sparanoid.com

# fire up a localhost and auto generate when files change
auto: true
server: ture
server_port: 4321

# exclude files for generated site
exclude: 
- README.md
- LICENSE
- Rakefile
- sparanoid-start.tmproj